#! /usr/bin/env python
# Test for various windowing functions
# Each window output plot in PLOTS_DIR

import pyDRC
import numpy as np
import matplotlib.pyplot as plt

PLOTS_DIR = "./plots"

def main():
    print("Plotting windowing functions script test")
    # Hamming Window
    ln = 200
    t = np.arange(0.0, 2.0, 0.01)
    s = pyDRC.Ones(ln)
    print("Hamming Window...")
    a = pyDRC.HammingWindow(s, 0, len(s))
    fig, ax = plt.subplots()
    ax.plot(t, a, linewidth = 0.8)
    ax.set(xlabel='X value', ylabel='Window value',title='Hamming window')
    ax.grid()
    ax.set_xlim(xmin=0,xmax=2.0)
    ax.set_ylim(ymin=0,ymax=1.0)
    fig.savefig("%s/hamming.png"%PLOTS_DIR)
    # Hanning Window
    s = pyDRC.Ones(ln)
    print("Hanning Window...")
    a = pyDRC.HanningWindow(s, 0 ,len(s))
    fig, ax = plt.subplots()
    ax.plot(t, a, linewidth = 0.8)
    ax.set(xlabel='X value', ylabel='Window value',title='Hanning window')
    ax.grid()
    ax.set_xlim(xmin=0,xmax=2.0)
    ax.set_ylim(ymin=0,ymax=1.0)
    fig.savefig("%s/hanning.png"%PLOTS_DIR)
    # Blackman Window
    s = pyDRC.Ones(ln)
    print("Blackman Window...")
    a = pyDRC.BlackmanWindow(s, 0, len(s))
    fig, ax = plt.subplots()
    ax.plot(t, a, linewidth = 0.8)
    ax.set(xlabel='X value', ylabel='Window value',title='Blackman window')
    ax.grid()
    ax.set_xlim(xmin=0,xmax=2.0)
    ax.set_ylim(ymin=0,ymax=1.0)
    fig.savefig("%s/blackman.png"%PLOTS_DIR)
    # Spaced left blackman window
    s = pyDRC.Ones(ln)
    print("Spaced Left Blackman Window...")
    a = pyDRC.SpacedBlackmanWindow(s, len(s), 30, 'WLeft')
    fig, ax = plt.subplots()
    ax.plot(t, a, linewidth = 0.8)
    ax.set(xlabel='X value', ylabel='Window value',title='Spaced blackman left window')
    ax.grid()
    ax.set_xlim(xmin=0,xmax=2.0)
    ax.set_ylim(ymin=0,ymax=1.0)
    fig.savefig("%s/blackman_left.png"%PLOTS_DIR)
    # Spaced right blackman window
    s = pyDRC.Ones(ln)
    print("Spaced Blackman Right Window...")
    a = pyDRC.SpacedBlackmanWindow(s, len(s), 30, 'WRight')
    fig, ax = plt.subplots()
    ax.plot(t, a, linewidth = 0.8)
    ax.set(xlabel='X value', ylabel='Window value',title='Spaced blackman right window')
    ax.grid()
    ax.set_xlim(xmin=0,xmax=2.0)
    ax.set_ylim(ymin=0,ymax=1.0)
    fig.savefig("%s/blackman_right.png"%PLOTS_DIR)
    # Spaced full blackman window
    s = pyDRC.Ones(ln)
    print("Spaced Blackman Full Window...")
    a = pyDRC.SpacedBlackmanWindow(s, len(s), 30, 'WFull')
    fig, ax = plt.subplots()
    ax.plot(t, a, linewidth = 0.8)
    ax.set(xlabel='X value', ylabel='Window value',title='Spaced blackman full window')
    ax.grid()
    ax.set_xlim(xmin=0,xmax=2.0)
    ax.set_ylim(ymin=0,ymax=1.0)
    fig.savefig("%s/blackman_full.png"%PLOTS_DIR)
    # Half left blackman window
    s = pyDRC.Ones(ln)
    print("Half Blackman Left Window...")
    a = pyDRC.HalfBlackmanWindow(s, len(s), 30, 'WLeft')
    fig, ax = plt.subplots()
    ax.plot(t, a, linewidth = 0.8)
    ax.set(xlabel='X value', ylabel='Window value',title='Half blackman left window')
    ax.grid()
    ax.set_xlim(xmin=0,xmax=2.0)
    ax.set_ylim(ymin=0,ymax=1.0)
    fig.savefig("%s/half_blackman_left.png"%PLOTS_DIR)
    # Spaced right blackman window
    s = pyDRC.Ones(ln)
    print("Half Blackman Right Window...")
    a = pyDRC.HalfBlackmanWindow(s, len(s), 30, 'WRight')
    fig, ax = plt.subplots()
    ax.plot(t, a, linewidth = 0.8)
    ax.set(xlabel='X value', ylabel='Window value',title='Half blackman right window')
    ax.grid()
    ax.set_xlim(xmin=0,xmax=2.0)
    ax.set_ylim(ymin=0,ymax=1.0)
    fig.savefig("%s/half_blackman_right.png"%PLOTS_DIR)
    # Bartlett window
    s = pyDRC.Ones(ln)
    print("Bartlett Window...")
    a = pyDRC.BartlettWindow(s, 0, len(s))
    fig, ax = plt.subplots()
    ax.plot(t, a, linewidth = 0.8)
    ax.set(xlabel='X value', ylabel='Window value',title='Barlett window')
    ax.grid()
    ax.set_xlim(xmin=0,xmax=2.0)
    ax.set_ylim(ymin=0,ymax=1.0)
    fig.savefig("%s/bartlett.png"%PLOTS_DIR)
    # Blackman-Harris window
    s = pyDRC.Ones(ln)
    print("Blackman-Harris Window...")
    a = pyDRC.BlackmanHarrisWindow(s, 0, len(s))
    fig, ax = plt.subplots()
    ax.plot(t, a, linewidth = 0.8)
    ax.set(xlabel='X value', ylabel='Window value',title='Blackman-Harris window')
    ax.grid()
    ax.set_xlim(xmin=0,xmax=2.0)
    ax.set_ylim(ymin=0,ymax=1.0)
    fig.savefig("%s/blackman-harris.png"%PLOTS_DIR)
    # Exponential window
    s = pyDRC.Ones(ln)
    print("Exponential Window...")
    a = pyDRC.ExponentialWindow(s, 3.0, 0, len(s))
    fig, ax = plt.subplots()
    ax.plot(t, a, linewidth = 0.8)
    ax.set(xlabel='X value', ylabel='Window value',title='Exponential window')
    ax.grid()
    ax.set_xlim(xmin=0,xmax=2.0)
    ax.set_ylim(ymin=0,ymax=1.0)
    fig.savefig("%s/exponential.png"%PLOTS_DIR)
    print("Final del test")

if __name__ == '__main__':
    main()
